"""Shared game settings and constants."""

# Screen
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
TARGET_FPS = 60

# Radii
PLAYER_RADIUS = 40
PIG_RADIUS = 40

# Health
PLAYER_MAX_HEALTH = 100
PIG_MAX_HEALTH = 100

# Movement / AI
PLAYER_BASE_SPEED = 300
PIG_SPEED = 150
CHASE_RANGE = 500

# Sword
SWORD_LENGTH = 60
SWORD_WIDTH = 14
PLAYER_DAMAGE = 20
PIG_DAMAGE = 5  # each pig deals 5 damage
PLAYER_SWING_TIME = 0.18  # seconds sword is "active"
PIG_SWING_TIME = 0.18
PLAYER_COOLDOWN = 0.5  # time before next swing
PIG_COOLDOWN = 0.5
PLAYER_SWING_DISTANCE = PLAYER_RADIUS + 8
PIG_SWING_DISTANCE = PIG_RADIUS + 8
SWING_ARC_DEG = 80  # total arc angle for sword swing animation

# Knockback
KNOCKBACK_SPEED = 420  # pixels per second pushed back
KNOCKBACK_DURATION = 0.18  # seconds of knockback

# Screen shake
SHAKE_INTENSITY = 8
SHAKE_DURATION = 0.15

# Shield
SHIELD_LENGTH = 36  # how far the shield extends forward
SHIELD_WIDTH = 36  # how wide the shield looks
SHIELD_DISTANCE = PLAYER_RADIUS - 6
SHIELD_MAX_BLOCKS = 5

# Potions and coins
POTION_HEAL = 30
START_POTION_COUNT = 1
COIN_VALUE = 5
COIN_PICKUP_RADIUS = 50
SPEED_POTION_COST = 10
SPEED_BOOST_MULT = 1.5

# Inventory
INVENTORY_SLOTS = 10

# Doors
DOOR_WIDTH = 40
DOOR_HEIGHT = 120
DOOR_MARGIN = 10
FIRST_ROOM_DOOR_WIDTH = 120
FIRST_ROOM_DOOR_HEIGHT = 180
FIRST_ROOM_DOOR_COLOR = (255, 255, 80)
FIRST_ROOM_DOOR_OUTLINE = (255, 255, 255)

# Visuals
FONT_SIZE = 26
BLOOD_LIFETIME = 0.6
